# Generated by Django 5.2.4 on 2025-07-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_bookingenquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingenquiry',
            name='venue',
        ),
        migrations.AddField(
            model_name='bookingenquiry',
            name='venues',
            field=models.ManyToManyField(to='application.venue'),
        ),
    ]
